### PR TITLE
Lm add a product

### PR DESCRIPTION
**Pull request by LukeAMiller**
Description
Sell A Product for a user
Related Ticket(s)
#1
Steps to Test

- If Database is not up to date then open Package Manager Console and type Update-Database and press enter
- Press green play button at the top of VS

- in the provided webpage register and login if you haven't already

- Click on the Sell A Product button in the navbar

- Fill in the required fields and Press Sell button

- You should be redirected to the Details Page of that Product

### CODE REVIEW

**Comment by AllxnCook** [comment]
Works as stated! No bugs
Great job!

**Comment by calebooski13** [comment]
Everything works as expected all except adding an image of the item you are trying to sell. 
The error i received was
The value 'data:image/jpeg;base64' is not valid for Image.

**Comment by AllxnCook** [comment]
WOULD YA JUST LOOK AT THEEAT! IT WORKS FANTASTICALLY

**Comment by LanceP51** [comment]
works fine for me

**Pull request merged**
