### PR TITLE
able to add a payment method

### PR DESCRIPTION
**Pull request by calebooski13**
##Description
Able to create/add payment method to account

##Related Ticket(s)
7
##Steps to Test

Please provide thorough instructions for how to manually test the changes on this PR.
Clone down BangazonSite/pig-pong git repository in Git Bash
CD into bangazon/pig-pong
CD into BangazonSite.sln
Run 'Start_BangazonSite.sln"

When Visual Studio opens up, you'll see a Green 'Play' button at the top of the program
Click that button and it will open a webpage of the BangazonSite project
Register a user and log in
Once logged in, click account name on top right 
Should see link saying "add payment method"
Click 
Fill in "Name", "Account Number"
Click Submit
Happy Testing!

Checklist:
[x] I have commented my code, particularly in hard-to-understand areas
[]I have made corresponding changes to the documentation
[]My changes generate no new errors
[]I have added tests that prove my fix is effective or that my feature works
[]New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AllxnCook** [comment]
After adding an account type, it is not adding to the list of payment options. Needs worked out

**Comment by LukeAMiller** [comment]
when adding a payment type it doesnt save boooo!

**Comment by LanceP51** [comment]
everything works now man, pmt type saves

**Comment by AllxnCook** [comment]
Good job fixing the issue. works well now. 
Would recommend a conditional for card number allowing it to have to be 16 digits in length.

**Comment by LukeAMiller** [comment]
my credit card number is 16

**Pull request merged**
